behaviors:
  DroneAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512           
      buffer_size: 4096
      # learning_rate: 1.0e-7
      #learning_rate: 1.0e-10
      # learning_rate: 0.0003
      learning_rate: 0.00003
      beta: 1.0e-3
      # beta: 1.0e-8
      # beta: 1.0e-2
      epsilon: 0.1
      lambd: 0.99
      num_epoch: 3
      # num_epoch: 2
      learning_rate_schedule: linear
      # learning_rate_schedule: cosine
      # learning_rate_schedule: constant
      # beta_schedule: constant
      beta_schedule: linear
      # beta_start: 0.001
      # beta_end: 0.00001
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 32
      num_layers: 2
      normalize: true
    reward_signals:
      extrinsic:
        # gamma: 0.9
        gamma: 1
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1.0e20
    time_horizon: 64
    summary_freq: 5000